#pragma once


enum EVENT_TYPE { EVENT_NPC_MOVE,EVENT_PLAYER_HILL };

enum COMP_OP { OP_RECV, OP_SEND, OP_ACCEPT, OP_NPC_MOVE, OP_PLAYER_MOVE,OP_PLAYER_HILL };

enum STATE { ST_FREE, ST_ACCEPT, ST_INGAME };